builds:
  - id: builder
    binary: "{{ .ProjectName }}"
    env:
      # Because we want to avoid coupling to system libraries.
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64

archives:
  - id: zip
    builds:
      - builder
    format: zip
    name_template: "{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}"
    wrap_in_directory: false
    files:
      - none*

checksum:
  disable: true
  name_template: "{{ .ProjectName }}_v{{ .Version }}_checksums.txt"

# signs:
#   - id: notarize
#     signature: "${artifact}.zip"
#     cmd: gon
#     args:
#       - ".gon.hcl"
#     artifacts: all
#     ids:
#       - builder

release:
  disable: true
  ids:
    - none
  extra_files:
    - glob: ./dist/*.zip
